config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :dogs
  resources :tags
  root 'pages#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/perritos-app/(*path)' => 'dogs#index'
end


app/models/dog.rb
class Dog < ApplicationRecord
  #Relationships
  belongs_to :user, primary_key: :id, foreign_key: :contact_id
  belongs_to :race, primary_key: :id, foreign_key: :race_id
  has_many :tags, through: :dog_tags
  has_many :dog_tags, dependent: :delete_all
  has_many :photos, dependent: :delete_all

  #Attributes Accesors
  attr_accessor :display_name, :tag_id, :image

  #Validations
  validates  :name, presence: true
  validates  :image, presence: true, on: :create
  validates  :latitude, presence: true
  validates  :longitude, presence: true
  validates  :description, presence: true

  #kaminari config
  paginates_per 6
  max_paginates_per 10
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :text
  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.where(contact_id: current_user.id)
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    respond_with(@dog)
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
    @selectedTag = params[:tagId]
    @contact_id = current_user.uid
    @dogSize = [['Pequeño','S'],['Mediano','M'],['Grande','L'], ['Extra Grande','X']]
    @dogSex = [['Femenino','F'],['Masculino','M']]
  end

  # GET /dogs/1/edit
  def edit
    @contact_id = @dog.contact_id
    @dog.tags.each do |tag| 
      @selectedTag = tag.id 
    end 
    respond_with(@dog)
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dog.contact_id = User.select('id').where(uid: dog_params[:contact_id]).first.id
    
    respond_to do |format|
      if @dog.save
        @photo = Photo.new({image: dog_params[:image], dog_id: @dog.id})
        @dogTag = DogTag.new(dog_id: @dog.id, tag_id: dog_params[:tag_id])
        
        if @photo.save
          if @dogTag.save
            if Dog.where(id: @dog.id).update_all(avatar_id: @photo.id)
              format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
              format.json { render :show, status: :created, location: @dog }
            else
              format.html { render :new }
              format.json { render json: @dog.errors, status: :unprocessable_entity }  
            end
          else  
            format.html { render :new }
            format.json { render json: @dogTag.errors, status: :unprocessable_entity }
          end 
        else
          format.html { render :new }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Los datos de "' + @dog.name + '" se actualizaron correctamente.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Los datos de "' + @dog.name + ' han sido borrados correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :contact_id, :image, :tags, :tag_id, :latitude, :longitude, :description, :sex, :age, :race_id, :size, :vaccines)
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog, :html => {:multipart => true, class: 'form-vertical', 'ng-controller': "GoogleMapController" }, validate: true do |f| %>
  <% if dog.errors.any? %>
    <div class="row" id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>
      <ul>
        <%= dog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="clearfix"></div>
  <%= f.input :contact_id, as: :hidden, input_html: { value: @contact_id } %>
  <%= f.input :tag_id, as: :hidden, input_html: { value: @selectedTag} %>
  <%= f.input :name, label: 'Nombre' %>
  <%= f.association :race, prompt: "Select the race of the dog", label: 'Raza' %>
  <div class="form-group">
    <% if !@dog.new_record? %>
      <div class="col-xs-12 col-sm-12 col-lg-4" ng-init="dog_id=<%= @dog.id %>">
        <% @dog.photos.each do |avatar| %>
          <% if avatar.id == dog.avatar_id %>
            <%= image_tag avatar.image.url(:thumb), alt: @dog.name, class: "img-responsive center-block" %>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <%= f.input :image, label: 'Foto', as: :file, class: 'btn-file' %>
      <div class="clearfix"></div>
    <% end %>
  </div>
  <div class="clearfix"></div>
  <%= f.input :sex, collection: @dogSex, prompt: "Selecciona el sexo del perro", label: 'Sexo' %>
  <%= f.input :age, label: 'Edad' %>
  <%= f.input :size, collection: @dogSize, prompt: "Selecciona el tamaño del perro", label: 'Tamaño' %>
  <%= f.input :vaccines, label: 'Vacunas' %>
  <ui-gmap-google-map center="map.center" zoom='map.zoom' events="map.events" id="maps"> 
    <ui-gmap-marker idKey="map.markers.id" coords="map.markers.coords"></ui-gmap-marker>
  </ui-gmap-google-map>
  <%= f.input :latitude, as: :hidden, input_html: {'ng-value': 'UserMarker.currentLatitude'} %> 
  <%= f.input :longitude, as: :hidden, input_html: {'ng-value': 'UserMarker.currentLongitude'}%>
  <%= f.input :description, label: 'Descripcion' %>
  <div class="clearfix"></div>
  <div class="actions">
    <div class="btn-group pull-right">
      <%= f.button :submit, 'Guardar', class: "btn btn-primary" %>
      <% if !@dog.new_record? %>
        <%= link_to 'Ver', @dog, class: 'btn btn-success' %>
      <% end %>
      <%= link_to 'Cancelar', dogs_path, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>
<%= javascript_include_tag 'perritos-app/application' %>

app/views/dogs/edit.html.erb
<h1>Editar información de <%= @dog.name %></h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>
<script type="text/javascript">
  $(document).ready(function(){
    initDogsForm();
  });
  
  // $(document).on('turbolinks:load', function(){
  //    angular.bootstrap(document.body, ['perritosApp'])
  // });
</script>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Mis Perros</h1>
<% @dogs.each do |dog| %>
  <div class="col-xs-6 col-sm-12 col-md-4 col-lg-4">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= link_to dog.name, dog, class: "btn btn-lg btn-link btn-block" %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
        <% dog.photos.each do |photoDog| %>
          <% if photoDog.id == dog.avatar_id %>
            <%= image_tag photoDog.image.url(:thumb), alt: dog.name, class: 'img-responsive center-block img-circle' %>
          <% end %>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-12">
        <center>
          <div class="btn-group">
            <%= link_to  dog, class: "btn btn-default btn-xs", title: "Ver informacion" do %>
              <i class="glyphicon glyphicon-eye-open"></i>
            <% end %>
            <%= link_to  edit_dog_path(dog), class: "btn btn-default btn-xs", title: "Editar información" do %>
              <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
            <%= link_to  dog, method: :delete, data: { confirm: 'Deseas borrar a ' + dog.name }, class: "btn btn-default btn-xs", title: "Borrar perro" do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>
            <%= link_to  new_photo_path(dogId: dog.id), class: "btn btn-default btn-xs", title: "Agregar fotos" do %>
              <i class="glyphicon glyphicon-camera"></i>
            <% end %>
          </div>
        </center>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <% dog.tags.each do |tag| %>
        <center>
          <%= content_tag :span, tag.name, class: "label label-danger"  %>
        </center>            
      <% end %>
    </div>
  </div>
<% end %>
<div class="clearfix"></div>
<br/>

app/views/dogs/new.html.erb
<h1>Registrar Un Perro</h1>

<%= render 'form', dog: @dog %>

<script type="text/javascript">
  $(document).ready(function(){
    initDogsForm();
  });
  // $(document).on('turbolinks:load', function(){
  //    angular.bootstrap(document.body, ['perritosApp'])
  // });
</script>

app/views/dogs/show.html.erb
<div class="col-xs-12 col-lg-12">
  <% if flash[:notice] %>
    <p id="notice" class="alert alert-success text-center">
      <%= notice %>
    </p>
  <% end %>
</div>

<div class="clearfix"></div>
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
    <div class="close">
      <% @dog.tags.each do |tag| %>
        <%= content_tag :span, tag.name, class: "label label-danger"  %>
      <% end %>
    </div>
    <h4 class="modal-title">
      <%= @dog.name %>
    </h4>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-7 col-lg-12">
        <% @dog.photos.each do |photoDog| %>
          <% if photoDog.id == @dog.avatar_id %>
            <%= image_tag photoDog.image.url(:medium), alt: @dog.name, class: 'img-responsive center-block img-circle' %>
          <% end %>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-5 col-lg-12">
        <div id="dogInfo">
          <ul>
            <li>
              <a href="#descriptionDog">
                <%= fa_icon "info-circle" %>
                Acerca 
              </a>
            </li>
            <li>
              <a href="#galeryDog">
                <%= fa_icon "camera" %>
                Fotos
              </a>
            </li>
            <li>
              <a href="#contactDog">
                <%= fa_icon "user-circle-o" %>
                Contacto
              </a>
            </li>
          </ul>
          <div id="descriptionDog">
            <div class="row wrapable-text">
              <%= @dog.description %>
            </div>
            <div class="row">
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                Vacunas
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                <%= @dog.vaccines %>
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                Raza
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                <%= @dog.race.name %>
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                Edad
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                <%= @dog.age %>
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                Sexo
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                <%= @dog.sex %>
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                Tamaño
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
                <%= @dog.size %>
              </div>
            </div>
          </div>
          <div id="galeryDog">
            <div class="row">
              <div class="panel panel-default">
                <div class="clearfix">
                  <%= link_to  new_photo_path(dogId: @dog.id), class: "btn btn-default pull-right" do %>
                    <%= fa_icon "picture-o" %>
                    Agregar foto
                  <% end %>  
                </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <% @dog.photos.each do |photoDog| %>
                  <% if photoDog.id != @dog.avatar_id && photoDog.image.exists?(:thumb) %>
                    <div class="col-xs-6 col-lg-3">
                      <%= link_to image_tag(photoDog.image.url(:thumb) , class: 'img-responsive center-block img-thumbail'), image_path(photoDog.image.url(:large)), data: {lightbox: @dog.name} %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div id="contactDog">
            <%= link_to current_user.name, 'https://www.facebook.com/'+current_user.uid %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-lg-12">
          
        </div>
        <div class="clearfix"></div>
        <div class="col-xs-12 col-sm-12 col-lg-12">
          <div class="btn-group">
            <%= link_to   dogs_path, class: "btn btn-default", title: "Back" do %>
              <i class="glyphicon glyphicon-arrow-left"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    initDogs();
  })
  .on('turbolinks:load', function(){
    angular.bootstrap(document.body, ['myApp'])
  });
</script>