config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :dogs
  resources :tags
  root 'pages#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/perritos-app/(*path)' => 'dogs#index'
end


app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :dog
  
  has_attached_file  :image, styles: { large: "600x600#", medium: "300x300#", thumb: "150x150#" }

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:edit, :update, :destroy]
  before_action :set_dog, only: [:new]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @dogId = params[:dogId]
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.json { render json: { success: true, fileID: @photo.id  }, status: 200}
      else
        format.json {render json: { error: @image.errors.full_messages.join(',')}, status: 400}
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    if @photo.destroy
      render json: { message: "File deleted from server" }
    end 
    # respond_to do |format|
    #   # format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
    #   # format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:dog_id, :image)
    end

    def set_dog
      @dog = Dog.find(params[:dogId])
    end 
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="container">
  <%= simple_form_for @photo, :html => { :multipart => true, :class => "dropzone"  } do |f| %>
    <%= f.input :dog_id, as: :hidden, input_html: { value: @dogId} %>
    <div class="fallback">  
      <%= f.file_field :image, multiple: true %>
      <%= f.button :submit, class: "btn btn-sm btn-primary center-block" %>
    </div>

  <% end %>

  <div class="index">
  </div>
  <%= link_to 'Cancelar', @dog, class: 'btn btn-danger' %>
</div>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fotos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>Agregar fotos</h1>

<%= render 'form', photo: @photo %>

<script type="text/javascript">
  $(document).ready(function(){
    dropzoneLoad();
  });

</script>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @photo.avatar.url(:medium) %>